- rockcraft/oci.py
- rockcraft/providers/_lxd.py
- tests/unit/providers/conftest.py
- tests/unit/providers/test_lxd.py
Map the directory owner when mounting project from host instead of
using the uid of the current user, otherwise file creation will fail in hosts
where the directory owner and user id are different (like in gce spread
tests).
-----
> providers: fix id mapping in lxd project mount

- requirements-dev.txt
- requirements-doc.txt
- requirements.txt
Build instances are significantly faster to warm-start using craft-providers 1.2.0.
-----
> requirements: update craft-providers

- docs/index.rst
- docs/reference.rst
- docs/tutorials.rst
- rockcraft/lifecycle.py
- rockcraft/oci.py
- rockcraft/project.py
- tests/spread/general/craftctl/task.yaml
- tests/spread/general/entrypoint/rockcraft.yaml
- tests/spread/general/entrypoint/task.yaml
- tests/spread/general/environment/rockcraft.yaml
- tests/spread/general/environment/task.yaml
- tests/spread/tutorials/basic/task.yaml
- tests/unit/test_oci.py
- tests/unit/test_project.py
Allow rockcraft projects to specify the entrypoint and cmd of the
generated OCI images, and define the container environment.
-----
CRAFT-811
> project: add entrypoint, cmd and env properties

- tests/unit/test_project.py
Use "tmp_path" to isolate test data and keep the result of "make
test-units" clean.
I want to do some more cleaning-up but I figured I'd get this 'easy' fix out of the way
> cleanup: don't write test files in cwd

- rockcraft/oci.py
Removed all occurrences to the :type role within the doc-strings.
Fixes : https://github.com/canonical/rockcraft/issues/58
> removed all occurrences to :type

- rockcraft/errors.py
- rockcraft/parts.py
- rockcraft/project.py
- rockcraft/providers/__init__.py
- rockcraft/providers/_lxd.py
- rockcraft/providers/_multipass.py
- rockcraft/providers/_provider.py
- tests/unit/test_project.py
Instead of having the definition of custom exceptions spread out through different files, this refactoring brings all the Rockcraft exceptions into a single and common error.py file.
-----
> feat: refactor all errors into reusable module

- tests/spread/general/big/rockcraft.yaml
- tests/spread/general/big/task.yaml
This new test can be used to "house" multiple different checks without
having to "setup" and "teardown" the whole machinery multiple times.
This initial version tests bug #44, regarding permissions of added
directories.
-----
@sergiusens @cmatsuoka this is an attempt at adding a spread test that we can augment over time, as discussed last week. Thanksss
> spread: add a "big" spread test

- rockcraft/cli.py
- rockcraft/commands/__init__.py
- rockcraft/commands/lifecycle.py
- rockcraft/lifecycle.py
- rockcraft/parts.py
- tests/unit/test_cli.py
- tests/unit/test_parts.py
Implement rockcraft commands for the parts lifecycle steps pull,
overlay, build, stage, and prime. Originally implemented to debug
problems related to OCI whiteout files in part layers.
-----
> commands: add lifecycle step commands

- .github/workflows/tests.yaml
- Makefile
- requirements-dev.txt
- requirements-doc.txt
- requirements.txt
- rockcraft/cli.py
- rockcraft/lifecycle.py
- rockcraft/oci.py
- rockcraft/parts.py
- setup.cfg
- tests/unit/test_project.py
Some minor code updates to reflect the Emitter changes, following the
steps taken in charmcraft's equivalent PR https://github.com/canonical/charmcraft/pull/801
Also did some minor housekeeping by enabling the 'pylint' linter in the linters CI job, and updating the 'autoformat' config to not _fix files in the virtualenv_ :scream:
> update craft-cli to 1.2.0

- rockcraft/providers/_buildd.py
- rockcraft/providers/_lxd.py
- rockcraft/providers/_multipass.py
- tests/unit/providers/test_buildd.py
- tests/unit/providers/test_lxd.py
- tests/unit/providers/test_multipass.py
-----
Use the new `craft-providers` API to install snaps inside a provider.  No functional changes.
(CRAFT-1347)
> providers: install rockcraft snap via craft-providers API

- rockcraft/providers/_lxd.py
- rockcraft/providers/_multipass.py
- rockcraft/providers/_provider.py
- rockcraft/providers/providers.py
- tests/unit/providers/test_lxd.py
- tests/unit/providers/test_multipass.py
- tests/unit/providers/test_provider.py
- tests/unit/providers/test_providers.py
-----
`get_instance_name()` is a rockcraft-specific function, so it is moved to providers.py
(CRAFT-1350)
> providers: move get_instance_name() to providers.py

- requirements-dev.txt
- requirements.txt
- rockcraft/parts.py
Use the common part validator implemented in craft-parts to validate part data against part and plugin models, and drop the local implementation.
-----
> parts: use part validator from craft-parts

- rockcraft/cli.py
-----
When `rockcraft` is running in managed mode (i.e. inside an instance), then save the log file.
Referenced from [snapcraft](https://github.com/snapcore/snapcraft/blob/9e10fd1b658df80c35e1996cd92a077e831a8d51/snapcraft/cli.py#L166).
> cli: capture logs in logfile

- rockcraft/lifecycle.py
-----
Previously, calling `rockcraft --verbosity=debug` and `rockcraft --verbosity=trace` would fail here.
Referenced from [snapcraft](https://github.com/snapcore/snapcraft/blob/9e10fd1b658df80c35e1996cd92a077e831a8d51/snapcraft/parts/lifecycle.py#L489).
> lifecycle: use new verbosity levels

- rockcraft/lifecycle.py
- rockcraft/providers/_lxd.py
- rockcraft/providers/_multipass.py
- rockcraft/providers/_provider.py
- tests/unit/providers/test_lxd.py
- tests/unit/providers/test_multipass.py
-----
Another bite-sized chunk of separating application-specific logic out of the `Provider` classes.
`get_instance_name()` is a rockcraft-specific function, so it is now called from `lifecycle.py`.
(CRAFT-1379)
> providers: move `get_instance_name()` call to lifecycle.py

- rockcraft/lifecycle.py
- rockcraft/providers/_lxd.py
- rockcraft/providers/_multipass.py
- rockcraft/providers/_provider.py
- rockcraft/providers/providers.py
- tests/unit/providers/test_lxd.py
- tests/unit/providers/test_multipass.py
- tests/unit/providers/test_providers.py
-----
Configuring a base is specific to rockcraft, so it is:
1. encapsulated in a function and moved to `providers.py` 
2. called by `lifecycle.py` instead of the Provider classes `lxd.py` and `multipass.py`
(CRAFT-1380)
> providers: move base configuration logic to providers.py

- Makefile
- rockcraft/lifecycle.py
- tests/unit/conftest.py
- tests/unit/test_lifecycle.py
-----
New unit tests for `lifecycle.py::_run_in_provider()`.  I referenced `charmcraft`'s unit testing, but it was still quite challenging to mock.
Before:
```
Name                     Stmts   Miss  Cover
--------------------------------------------
rockcraft/lifecycle.py      90     76    16%
```
After:
```
Name                     Stmts   Miss  Cover
--------------------------------------------
rockcraft/lifecycle.py      90     58    36%
```
> tests: test lifecycle.py::_run_in_provider

- rockcraft/cli.py
- rockcraft/errors.py
- rockcraft/lifecycle.py
- rockcraft/providers/__init__.py
- rockcraft/providers/_lxd.py
- rockcraft/providers/_multipass.py
- tests/unit/providers/test_lxd.py
- tests/unit/providers/test_multipass.py
- tests/unit/test_cli.py
-----
Use `ProviderError` from craft-providers.
> providers: use ProviderError from craft-providers

- rockcraft/lifecycle.py
- rockcraft/providers/_lxd.py
- rockcraft/providers/_multipass.py
- rockcraft/providers/providers.py
- tests/unit/providers/test_lxd.py
- tests/unit/providers/test_multipass.py
- tests/unit/test_lifecycle.py
-----
*craft applications have a concept of a "base".  This base is translated a `craft-providers` base and is passed to `craft-providers` so it can choose which base image (OS and release) to use for the instance.
Currently, each application translates its own base inside `_lxd.py` and `_multipass.py`.  This application-specific code needs to be removed from these files.
To support this, I created a list of what bases `craft-providers` can accept.  Right now, `18.04`, `20.04`, and `22.04` are supported.  Other OSs and releases can be added in the future without breaking backwards compatibility.
The image below shows how an application can translates its base to a `craft-providers` base.   It also shows `craft-providers` translating it to the specific name needed for LXD and Multipass to …
> providers: translate rockcraft base to provider base

- rockcraft/lifecycle.py
- rockcraft/providers/_lxd.py
- rockcraft/providers/_multipass.py
- tests/unit/providers/test_lxd.py
- tests/unit/providers/test_multipass.py
- tests/unit/test_lifecycle.py
-----
Mounting the project directory is a rockcraft-specific step, so it is moved out of the craft-providers interface.
Blocked by https://github.com/canonical/craft-providers/pull/154
(CRAFT-1381)
> providers: move mount logic to lifecycle.py

- .github/workflows/tests.yaml
-----
The `macos-10.15` action runner is [being deprecated on 2022-Dec-01](https://github.com/actions/runner-images/issues/5583).
There are scheduled brown-outs to warn developers, which I encountered [here](https://github.com/canonical/rockcraft/actions/runs/3113458595)
Valid replacements are `macos-11`, `macos-12`, and `macos-latest`.  I chose `macos-latest`.
> tests: update macos from 10.15 to latest

- requirements-dev.txt
- requirements.txt
- snap/snapcraft.yaml
- tests/spread/general/chisel/rockcraft.yaml
- tests/spread/general/chisel/task.yaml
This PR lets rockcraft support chisel slices in stage-packages. 
Notes:
- "chisel" is added directly on rockcraft's snap, just like skopeo and 
umoci, as it's only an "image-build-time" dependency;
- We currently pin `craft-parts` to a specific commit on `main` because
we don't yet have a release of craft-parts with chisel support, but 
that should come soon;
- The added spread test uses the dotnet-runtime-6.0_libs slice, and 
currently overrides `prime` to create symlinks because the internal 
directory structure of the slice changes with new versions. This will
be addressed/discussed in the future.
CRAFT-1333
> Add chisel to rockcraft

- rockcraft/lifecycle.py
- rockcraft/providers/_lxd.py
- rockcraft/providers/_multipass.py
- rockcraft/providers/_provider.py
- rockcraft/providers/providers.py
- tests/unit/conftest.py
- tests/unit/providers/test_lxd.py
- tests/unit/providers/test_multipass.py
- tests/unit/providers/test_providers.py
- tests/unit/test_lifecycle.py
-----
Two changes:
1. `confirm_with_user()` is a rockcraft-specific call, so it is moved out of the craft-providers interface.
- The user confirmation logic was split out to `providers.py`
- `lxd.py` and `multipass.py` still handle the installation and ensure the provider is available
3. Rename `is_provider_available()` to `is_provider_installed()`
(CRAFT-1387)
> providers: move `confirm_with_user()` call to providers.py

- rockcraft/cli.py
- rockcraft/commands/__init__.py
- rockcraft/commands/lifecycle.py
- rockcraft/lifecycle.py
- tests/unit/test_lifecycle.py
-----
Add command `rockcraft clean` with stubbed out TODOs.  This lays down groundwork needed to refactor `clean_project_environments()`.
There are 3 ways the `clean` command is used:
- cleans a specific part
- added as a TODO to be implemented later
- cleans the local build environment
- added as a TODO, but users shouldn't encouter this, since `destructive mode` is also unsupported and labeled with a TODO
- cleans a provider environment
- added as a TODO, but will be supported in my next PR
(CRAFT-1394)
> commands: add clean command

- spread.yaml
- tests/spread/general/bare-base/task.yaml
- tests/spread/general/big/task.yaml
- tests/spread/general/chisel/task.yaml
- tests/spread/general/craftctl/task.yaml
- tests/spread/general/entrypoint/task.yaml
- tests/spread/general/environment/task.yaml
- tests/spread/tutorials/basic/task.yaml
The commands in `restore-each` are run after each task, which lets us cleanup docker images/lxc containers/etc without having to "remember" to do it per-task.
-----
> spread: add 'global' clean-up calls

- README.rst
-----
Start pointing to RTD.com for the documentation. The new RTD project is owned by @evildmp . It removes ads from our docs. The README in this PR points to the new docs and includes an updated badge for the docs status.
The old docs are now redirecting to the new ones.
> docs: migrate to RTD.com

- requirements-dev.txt
- requirements-doc.txt
- requirements.txt
-----
Building a ROCK with revision 309 produces the error:
```
craft-providers error: failed to inject host's snap 'rockcraft' into target environment.   
...                                                                                                                                                
error: cannot assert: assert failed: cannot resolve prerequisite assertion: account (pMLNwd28ezFdozetvrAOlLj3UqC9HKpe)
```
This error is fixed in https://github.com/canonical/craft-providers/pull/159 and `craft-providers` v1.5.1.
> requirements: update craft-providers to v1.5.1

- spread.yaml
The spread run only needs the 'test/' and 'tools/' dir. This change has little impact on CI runs because they start from a 'clean' checkout, but for local runs the behavior of adding everything can add hundreds of MB of local 'junk' (specially from the virtual environment). So this speeds up local runs a bit.
-----
> spread: restrict the files we package

- rockcraft/lifecycle.py
- rockcraft/providers/_lxd.py
- rockcraft/providers/_multipass.py
- rockcraft/providers/_provider.py
- tests/spread/general/clean/rockcraft.yaml
- tests/spread/general/clean/task.yaml
- tests/unit/conftest.py
- tests/unit/providers/test_lxd.py
- tests/unit/providers/test_multipass.py
- tests/unit/providers/test_provider.py
- tests/unit/test_lifecycle.py
-----
Support the command `rockcraft clean` to clean a rockcraft environment (i.e. delete a LXD instance).
I'm following the same implementation recently done in [snapcraft](https://github.com/snapcore/snapcraft/pull/3875) and [charmcraft](https://github.com/canonical/charmcraft/pull/835), where instances are deleted via the `Executor` object.
(CRAFT-1373)
> providers: support `rockcraft clean` for a rockcraft environment

- rockcraft/providers/_lxd.py
- rockcraft/providers/providers.py
- tests/unit/providers/test_lxd.py
- tests/unit/providers/test_providers.py
-----
I promise this is my last `rockcraft` PR today :laughing: 
This PR pulls out rockcraft's project name out of `lxd.py` and moves it to `providers.py`.
> providers: move lxd project name out of craft-providers interface

- rockcraft/cli.py
- rockcraft/commands/lifecycle.py
-----
closes https://github.com/canonical/rockcraft/issues/112
Move `init` out of the lifecycle commands and fixes the help messages that were inherited from snapcraft.
> fix: #112 and help messages

- tests/unit/providers/test_providers.py
-----
Tiny change to a unit test.
The test fixture `providers/conftest.py::mock_path` is leaving rockcraft, so I removed the only reference to it inside rockcraft's test suite.
> tests: use tmp_path instead of mock_path

- requirements-dev.txt
- requirements.txt
- tests/spread/general/entrypoint/rockcraft.yaml
Craft-parts 1.15.1 fixes device nodes in the overlay base image. This should address issues related to package list updates when using base ubuntu:22.04. (Fixes #117)
-----
> requirements: update craft-parts to 1.15.1

- spread.yaml
Disable spread runs on fedora until it runs kernel >=6.0.7 (currently in testing) because of the squashfs bug that affects snapd.
Refs:
- https://forum.snapcraft.io/t/unsupported-version-0-of-verneed-record-linux-6-0/32160/14
- https://bodhi.fedoraproject.org/updates/?packages=kernel
-----
> spread: disable fedora due to squashfs bug

- rockcraft/providers.py
- tests/unit/test_providers.py
-----
Captured logs were not being saved to the log file in quiet and brief modes because they were emitted as trace-level messages instead of debug-level.
This is an identical fix from snapcraft: https://github.com/snapcore/snapcraft/pull/3950
Resolves https://github.com/canonical/rockcraft/issues/140
> providers: capture logs with debug-level logging

- spread.yaml
This reverts commit 5a78d6dd86892b86a02344e13db4d2c36b7c4772.
Kernel 6.0.7 is now available on the Fedora images used by spread.
-----
> Revert "spread: disable fedora due to squashfs bug (#142)"

- rockcraft/project.py
- tests/unit/test_project.py
This allows a rockcrafter to install whatever version of go they would required.
Signed-off-by: Sergio Schvezov <sergio.schvezov@canonical.com>
-----
> project: use isolated go to build pebble

- rockcraft/project.py
- tests/spread/general/plugin-go/go.mod
- tests/spread/general/plugin-go/hello.go
- tests/spread/general/plugin-go/rockcraft.yaml
- tests/spread/general/plugin-go/task.yaml
- tests/unit/test_project.py
This avoids a conflict when the user's go is installed.
Signed-off-by: Sergio Schvezov <sergio.schvezov@canonical.com>
-----
> project: install pebble's go without aliases setup

- requirements-dev.txt
- requirements-doc.txt
- requirements.txt
-----
This disables [automatic snap refreshes](https://github.com/canonical/craft-providers/pull/182) inside of instances.
Source: https://bugs.launchpad.net/snapcraft/+bug/1998100
(CRAFT-1520)
> dependencies: update craft-providers to 1.6.2

- rockcraft/oci.py
- tests/integration/test_oci.py
- tests/spread/general/big/rockcraft.yaml
- tests/spread/general/big/task.yaml
- tests/unit/test_oci.py
Now that add_layer() looks at the base, improve its logic to support
*explicit* removals/hiding of base layer symlinks. With this change,
regular directories created by lifecycle's "build" step will respect
symlinks in the base layer, but removals via overlay-scripts will
hide those symlinks.
> oci: handle opaque whiteouts in new layer (usrmerge) 

- rockcraft/cli.py
- rockcraft/errors.py
- rockcraft/oci.py
- spread.yaml
- tests/unit/test_cli.py
Implement a base class for Rockcraft errors for better organization, instead of using Craft-CLI's `CraftError` directly.
-----
> errors: add rockcraft error base class

- rockcraft/cli.py
- spread.yaml
The log path inside the managed instance is not directly accessible from the outer environment, so don't display it when ending the execution with an error message.
Co-authored-by: Facundo Batista <facundo@taniquetil.com.ar>
-----
> cli: don't expose the managed instance logpath

- rockcraft/errors.py
- rockcraft/parts.py
- spread.yaml
- tests/unit/test_parts.py
The previous code was using the PartsError string representation (via str(err)) to populate a PartsLifecycleError's message. This has the effect of adding the original error's `details` into the message, which bypasses craft_cli's error reporting based on verbosity levels.
-----
(CRAFT-1538)
> parts: fix conversion of PartsError

- Makefile
- docs/README.rst
- docs/explanation.rst
- docs/how-to/build-docs.rst
- docs/how-to/create-slice.rst
- docs/how-to/get-started.rst
- docs/how-to/index.rst
- docs/how-to/install-slice.rst
- docs/how-to/publish-slice.rst
- docs/index.rst
- docs/reference.rst
- docs/tutorials/chisel.rst
- docs/tutorials/index.rst
Use the already-enabled sphinx-lint tool to enforce 80 characters max per line, to facilitate review. Also enable *all* sphinx-lint linters, which in this case just mean some minor fixes.
Unfortunately we can't use tools like rstfmt because our docs have deviated enough from "standard" rst (using sphinx-only directives) that the tools fail to parse the source. This is a "next best thing" in that sphinx-lint doesn't format the docs, but can at least check it.
-----
(CRAFT-1503)
> docs: force max line length of 80 characters

- rockcraft/project.py
- spread.yaml
- tests/spread/general/big/task.yaml
- tests/unit/test_project.py
Now that pebble has been published as a snap we can use it directly instead of building the binary each time. Prime only the binary and "organize" it as /usr/bin/pebble just like the previous part did.
-----
(CRAFT-1566)
> project: use pebble snap instead of building

- docs/how-to/code/rockcraft-pack-action/rockcraft-pack.yaml
- docs/how-to/code/rockcraft-pack-action/task.yaml
- docs/how-to/index.rst
- docs/how-to/rockcraft-pack-action.rst
-----
A new `rockcraft-pack`  GH action has been created at https://github.com/canonical/craft-actions#rockcraft-pack.
This PR adds a how-to guide to the Rockcraft docs, instructing how to add this action to a GitHub Actions workflow, and referring to the original action's docs for more info.
> docs: add how-to guide for the rockcraft-pack GH action

- requirements-dev.txt
- requirements-doc.txt
- requirements.txt
Craft-parts 1.18.1 fixes ignored file patterns when processing local sources.
-----
> requirements: update craft-parts to 1.18.1

- requirements-dev.txt
- requirements-doc.txt
- requirements.txt
-----
Update to craft-providers v1.7.2, which includes performance improvements when launching LXD instances.
<details><summary>Changelog</summary>
<p>
1.7.2 (2023-02-06)
------------------
- Check LXD id map before starting an existing instance.
If the id map does not match, the instance will be auto cleaned
or an error will be raised.
- Add `lxc.config_get()` method to retrieve config values
1.7.1 (2023-01-23)
------------------
- Set LXD id maps after launching or copying an instance
- Raise BaseConfigurationError for snap refresh failures
1.7.0 (2023-01-11)
------------------
- LXD instances launch from a cached base instance rather than a base image.
This reduces disk usage and launch time.
- For the LXD launch function `launched_environment`, the parameter `use_snapshots`
has been …
> requirements: update craft-providers to 1.7.2

- snap/hooks/remove
- spread.yaml
- tests/spread/general/remove-hook/task.yaml
- tools/spread/install_rockcraft
-----
When removing rockcraft, the snap remove hook will delete rockcraft's images, instances, and project from LXD.
Similar to https://github.com/snapcore/snapcraft/pull/4014, except the snapcraft hook is currently very conservative and only deletes base instances and images.  The rockcraft remove hook is more useful and deletes all LXD data created by rockcraft.
:heavy_check_mark: the remove hook is tested by `shellcheck`
(CRAFT-1345)
> snap: add remove hook to delete rockcraft data from lxd

- spread.yaml
-----
The spread tests are failing to install lxd 5.9.
The snap channel for lxd 5.9 is now unlisted and can't be directly installed.  I filed a bug report https://bugs.launchpad.net/snapstore-server/+bug/2008114
Follow latest.  
```bash
snap install lxd --channel=latest/stable
```
:x: fails
Pin to another release.
```bash
snap install lxd --channel=5.10/stable  # or 5.11/candidate
```
:x: [Error from 5.10/stable](https://github.com/canonical/rockcraft/actions/runs/4245088818/jobs/7380328437).
:x: [Error from 5.11/candidate](https://github.com/canonical/rockcraft/actions/runs/4245574447/jobs/7381414281).
Workaround to stay on 5.9
```bash
snap install lxd --channel=latest/stable
snap refresh lxd --channel=5.9/stable
```
:heavy_check_mark: succeeds
> tests: bump lxd to 5.11 in spread tests

- rockcraft/oci.py
- tests/spread/general/big/rockcraft.yaml
- tests/spread/general/big/task.yaml
- tests/spread/general/usrmerge/rockcraft.yaml
- tests/spread/general/usrmerge/task.yaml
- tests/unit/test_oci.py
The scenario that was broken was: a payload like "bin/dir1/dir2" where "bin" is a symlink to somewhere on the lower (base) layer. The subdirs "dir1" and "dir2" were being incorrectly placed in "bin" instead of in the symlink target.
This broke quite a few plugins that place file trees in places like "lib/".
-----
CRAFT-1605
> oci: fix handling of subdirs in usrmerge

- rockcraft/oci.py
- tests/unit/test_oci.py
Docker Hub is fast but the Ubuntu images are updated infrequently and
the registry itself has pull limits for anonymous users. This limit is
annoying because currently rockcraft does not caching of base images.
The caching is coming, but in the meantime switch to Amazon ECR. The
registry has newer images and is only a little bit slower (from testing)
than Docker Hub).
> oci: use alternative registry

- rockcraft/errors.py
- rockcraft/oci.py
- tests/integration/test_oci.py
- tests/spread/general/usrmerge/rockcraft.yaml
- tests/spread/general/usrmerge/task.yaml
- tests/unit/test_oci.py
Reviewing note: the first commit restructures the code a bit without functional changes; the second commit has the actual bugfix.
=================
The situation is this: the primed payload has two distinct directories
(e.g. bin/dir1 and usr/bin/dir1) that, because of the usrmerge handling,
"point" to the same location (in this case, /usr/bin/dir1). We check
that the two directories have the same attributes (ownership and mode)
and then add a single entry to the layer (either one, they are all
equivalent).
All other cases (dirs with different attributes, conflicts between
files) raise errors. The reason for this is that we haven't seen this
come up "in the wild" yet, and it's hard to choose a behavior when we
don't know the circunstances.
(CRAFT-1634)
> oci: handle duplicate directories because of usrmerge 

- requirements-dev.txt
- requirements-doc.txt
- requirements.txt
-----
Update craft-providers to 1.8.0. 
The main value-add for rockcraft users is the auto-cleaning of instances that are interrupted during setup.
------------------
- **Track if instances are properly setup when launching. If the instance did not fully
complete setup and auto-clean is enabled, the instance will be cleaned and recreated.**
- Add new field `setup` to instance configuration to track set up status
- Update base compatibility tag from `base-v0` to `base-v1`
- Add new BuilddBaseAliases for Lunar and Kinetic
- Add support for interim Ubuntu releases for LXD
- Add support for custom LXD image remotes. LXD remotes can now add any
remote server to retrieve images from using the `RemoteImage` class.
- Add deprecation warning for LXD function `configure_buildd_image_remote()`. …
> requirements: update craft-providers to 1.8.0

- .github/workflows/tests.yaml
-----
The ubuntu-18.04 runner will be [fully unsupported](https://github.com/actions/runner-images/issues/6002) on 2023-Apr-01.
Today it is offline and breaking the workflow.
Note that it will be unsupported, not unavailable.  It will still be available for about 3 more months (2023-Jul).
> ci: remove ubuntu-18.04 runner from github workflow

- requirements-dev.txt
- requirements.txt
- spread.yaml
Craft-parts 1.18.4 makes the /dev rbind mount private, fixing chroot and overlayfs mounts when using lxd 5.11.
Fixes #195.
-----
> requirements: update craft-parts to 1.18.4

- rockcraft/oci.py
- tests/unit/test_oci.py
When Rockcraft creates the tar archive from the priming area, subdirs symlinks are skipped from archive.
Solution is to add subdirs when they are symlinks.
Fix #208
- [] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
-----
> oci: fix handling of symlink subdirs

- requirements-dev.txt
- requirements-doc.txt
- requirements.txt
- rockcraft/parts.py
- tests/util.py
Craft-parts 1.19.0 requires overlays to be enabled. Also update OS verifcation in tests now that Ubuntu-specific codenames were removed from Craft Parts' OSRelease.
-----
> requirements: update craft-parts to 1.19.0

- rockcraft/oci.py
- spread.yaml
- tests/unit/test_oci.py
The original `restore-each` removes all instances, including the base one! With this fix we should be able to reuse the base instance between compatible tests.
> spread: don't remove the base instance in cleanup

- rockcraft/commands/lifecycle.py
- rockcraft/lifecycle.py
- rockcraft/parts.py
- spread.yaml
- tests/spread/general/configure-hook/task.yaml
- tests/spread/general/remove-hook/task.yaml
- tests/unit/test_cli.py
- tests/unit/test_lifecycle.py
- tests/unit/test_parts.py
The implementation mimics Snapcraft's: if a lifecycle step fails, run a shell before propagating the error out.
-----
> cli, parts: support --debug

- docs/reference.rst
- rockcraft/project.py
Some leftover references to the defunct top-level 'env' entry were confusing users; update the example to move the environment definition to the Pebble service. Also fix some minor typos.
-----
> docs: remove references to 'env'

- rockcraft/oci.py
- tests/spread/general/usrmerge-file-collision/rockcraft.yaml
- tests/spread/general/usrmerge-file-collision/task.yaml
- tests/unit/test_oci.py
In c3382fc2408 we added support for directory collisions caused by the usrmerge when creating the payload layer; now we add support for file collisions if the files match in attributes and contents. This scenario can happen if an Ubuntu package is used both as an overlay-package and as a stage-package.
-----
> oci: support file collisions if the files match

- requirements-dev.txt
- requirements-doc.txt
- requirements.txt
Craft Parts 1.19.3 fixes plugin properties state during the
planning phase.
-----
> requirements: update craft-parts to 1.19.3

- rockcraft/oci.py
- tests/unit/test_oci.py
-----
Pebble currently does not show any logs from the service, making it impossible to know whether the service really works or not without running `pebble logs`. True to convention, we should make services log to stdout by default. 
Closes https://github.com/canonical/cos-alerter/issues/37
> make pebble write service logs to stdout by default

- tests/conftest.py
pyright 1.1.306 has updated checking that complains about accesses to unknown fields in `xdg`.
-----
> lint: add ignore for new pyright

- rockcraft/pebble.py
- rockcraft/project.py
- tests/spread/general/invalid-name/rockcraft.orig.yaml
- tests/spread/general/invalid-name/task.yaml
- tests/unit/test_project.py
Pebble only accepts lowercase a-z letters, numbers and hyphens. Since we use the ROCK's name on the layer file, use the same regex.
-----
> project: constrain ROCK name to pebble's rules

- spread.yaml
- tests/spread/general/repo-bare-base/rockcraft.yaml
- tests/spread/general/repo-bare-base/task.yaml
- tests/spread/general/repo-ubuntu-base/rockcraft.yaml
- tests/spread/general/repo-ubuntu-base/task.yaml
Rework a spread test to be less flaky, and update the systems to remove 18.04 and bump Fedora to 37.
> Spread updates

- requirements-dev.txt
- requirements-doc.txt
- requirements.txt
- tests/spread/general/plugin-python-error/rockcraft.orig.yaml
- tests/spread/general/plugin-python-error/task.yaml
Also adds a test that checks that a project that uses the Python plugin but does _not_ bundle the interpreter in its payload fails to build. This is important because the generated ROCK is otherwise completely unusable.
-----
> requirements: update craft-parts to 1.20.0

- spread.yaml
Latest version of the docker snap fails to install on Fedora with the following message:
```
error: cannot install "docker": snap "docker" assumes unsupported features:
snapd2.59.1 (try to refresh snapd)
```
Trying to refresh snapd doesn't actually solve the issue. While we investigage, installing from the older stable channel should keep the spread tests running.
Also do some minor cleanup from the fedora 36 -> 37 update.
-----
> spread: band-aid docker installation on fedora-37

- .github/workflows/spread-large.yaml
- spread.yaml
- tests/spread/large/init/task.yaml
Add a new spread suite, "tests/spread/large/", which runs on a cron of Sunday/Wednesday morning (2AM) *or* if a pull request gets the "run-large-spread" label.
-----
> ci, spread: add "large spreads" suite

- .github/workflows/tests.yaml
The macos-latest workers are frequently busy and the majority of the "interesting" tests are skipped on non-linux systems anyway. We can add the OS back in the future if we need to.
-----
> ci: remove test runs on macos-latest

- rockcraft/lifecycle.py
- rockcraft/parts.py
- tests/conftest.py
- tests/integration/plugins/test_python_plugin.py
- tests/integration/test_lifecycle.py
- tests/integration/test_oci.py
- tests/integration/test_parts.py
- tests/unit/test_lifecycle.py
- tests/unit/test_parts.py
The implementation follows Snapcraft's: a prologue callback is used to fill the project info with the project's name and version (the other 'useful' variables are already provided by craft_parts). This lets parts use those variables (for example during their builds).
A lot of the unit test changes come from a refactoring to make adding new parameters to parts.PartsLifecycle less painful in the future.
Closes #299
-----
> parts: add project-specific global variables

- pyproject.toml
- requirements-dev.txt
- requirements-doc.txt
- requirements.txt
- rockcraft/plugins/python_plugin.py
- tests/integration/plugins/test_python_plugin.py
- tests/spread/general/plugin-python-3.6/rockcraft.orig.yaml
- tests/spread/general/plugin-python-3.6/src/hello/__main__.py
- tests/spread/general/plugin-python-3.6/src/setup.py
- tests/spread/general/plugin-python-3.6/task.yaml
- tests/unit/plugins/test_python_plugin.py
Use ${PARTS_PYTHON_INTERPRETER} to play nice with the upstream plugin;
If the user overrides this, there's probably a good reason (like using
Python 3.6).
> plugins: fix python shebang

- docs/reference/rockcraft.yaml.rst
This PR add a warning note, about that the host need to be compatible with the arch written on the rockcraft.yaml file.
Signed_Off_By: Samir Akarioh <samir.akarioh@canonical.com>
-----
> docs: add warning for platforms field

- .github/ISSUE_TEMPLATE/docs.yaml
This is needed because the documentation link for
submitting new issues will direct the user to
the issues template selection page (since we do
not allow the creation of blank issues). Thus we should have a dedicated template for the docs where the
right labels and issue structure are applied.
-----
> docs: add new issue template for documentation

- docs/conf.py
- docs/reference/rockcraft.yaml.rst
- pyproject.toml
- rockcraft/lifecycle.py
- rockcraft/oci.py
- rockcraft/pebble.py
- rockcraft/project.py
- tests/spread/general/health-checks/rockcraft.yaml
- tests/spread/general/health-checks/task.yaml
- tests/unit/test_oci.py
- tests/unit/test_pebble.py
- tests/unit/test_project.py
-----
In this PR:
- move all Pebble-related schemas into the Pebble module
- add the schema for Pebble checks (based on https://github.com/canonical/pebble/#layer-specification)
- change the lifecycle logic to encompass the new `checks` field alongside the `services` field, when creating the Pebble layer
- add new field to reference documentation
> add support for health checks

- docs/how-to/convert-to-pebble-layer.rst
- docs/how-to/install-slice.rst
- docs/tutorials/chisel.rst
- docs/tutorials/hello-world.rst
- requirements-dev.txt
- requirements-doc.txt
- requirements.txt
- rockcraft/cli.py
- rockcraft/lifecycle.py
- rockcraft/oci.py
- rockcraft/providers.py
- tests/unit/conftest.py
- tests/unit/test_lifecycle.py
- tests/unit/test_providers.py
This PR does three things:
1) Bump versions of craft-parts, craft-providers and craft-cli;
2) Enables the "streaming brief" feature in craft-cli's Emitter, which makes it so that "info"-level messages get "streamed" inline with the current "progress" message when in Brief mode;
3) Cleans up some permanent progress messages related to packing the rock, so that the output in Brief mode is cleaner and more succint.
Here's a gif of the end result:
Fixes #345
> enable "streaming brief" CLI mode

- .github/workflows/snap.yaml
The workflow is not valid. .github/workflows/snap.yaml (Line: 41, Col:
13): Unrecognized named-value: 'SNAPCRAFT_STORE_CREDENTIALS'. Located
at position 1 within expression: SNAPCRAFT_STORE_CREDENTIALS != ''
-----
> fix(ci): correct conditional for snap publication

- requirements-dev.txt
- requirements-doc.txt
- requirements.txt
Craft Parts 1.25.1 adds numerous improvements to the Rust plugin.
-----
> build(deps): bump craft-parts from 1.24.1 to 1.25.1

- docs/how-to/use-flask-extension.rst
- docs/reference/extensions.rst
- rockcraft/extensions/flask_framework.py
- tests/unit/extensions/test_flask_framework.py
Provide a default prime list in the Flask extension for users' project files unless they supply their own.
If the user provides a prime list, it will replace the default one.
> Provide a default prime in the flask extension

- .github/workflows/tests.yaml
- .readthedocs.yaml
- docs/Makefile
- pyproject.toml
- requirements-bionic.txt
- requirements-focal.txt
- setup.cfg
- spread.yaml
This commit bumps the minimum required Python version to 3.10. Note that the application can still build ubuntu:20.04 images, this is about the code of the application itself.
Also add 3.12 testing on CI since that'll be the new standard version in ubuntu 24.04.
-----
> chore: drop ubuntu 20.04 and python 3.8

- spread.yaml
"re-use" is a [perfectly valid spelling](https://en.wiktionary.org/wiki/re-use), but this is easier than changing codespell settings every time we disagree with it
Fixes the codespell issue in #388 
-----
> style: change spelling for updated codespell

- requirements-dev.txt
- requirements-doc.txt
- requirements.txt
Craft Parts 1.25.2 fixes channel overrides in the Rust plugin,
validates part dependency names, and fixes environment variable
expansion.
-----
> build(deps): bump craft-parts from 1.25.1 to 1.25.2

- .github/workflows/tests.yaml
- .gitignore
- pyproject.toml
- rockcraft/__init__.py
- rockcraft/services/lifecycle.py
- setup.cfg
- snap/snapcraft.yaml
This commit pulls in the "dynamic" version setting (from git) from Starbase, and updates snapcraft.yaml to use that version (via adopt-info).
A consequence of this is that, in order to be able to run "python3 setup.py --version" without the dependencies installed, the enabling of the overlay feature is moved from ``rockcraft/__init__.py`` to the lifecycle service, which makes more sense any way as it's a feature specific to that service.
-----
> build: set version from git

- requirements-dev.txt
- requirements-doc.txt
- requirements.txt
-----
- Update base compatibility tag from ``base-v2`` to ``base-v3``
This fixes an issue where LXD instances created with
``craft-providers==1.16.0`` may fail to start with
``craft-providers>=1.17.0``.
- Require a disk device in the default LXD profile
> build(deps): bump craft-providers to 1.19.2

- requirements-dev.txt
- requirements-doc.txt
- requirements.txt
The current version has two bugs (the "looping timer" one and the "not collecting error logs" one) that are blocking for many users. Ideally we should merge main into this branch, this is a stopgap before we can allocate time for it.
-----
> chore(deps): update craft-providers to 1.19.2

- requirements-dev.txt
- requirements-doc.txt
- requirements.txt
- rockcraft/services/lifecycle.py
- rockcraft/services/package.py
Version 2.5.0 clears the "streaming brief" progress when calling emit.message() and emit.error(). Also cleanup some wrongly-permanent progress messages, to keep brief verbosity clean.
-----
> chore(deps): bump craft-cli

- rockcraft/layers.py
- rockcraft/services/lifecycle.py
- tests/integration/services/test_lifecycle.py
- tests/spread/general/prune/check_layers.py
- tests/spread/general/prune/rockcraft.yaml
- tests/spread/general/prune/task.yaml
- tests/testing/lifecycle.py
- tests/testing/project.py
- tests/unit/services/test_lifecycle.py
- tests/unit/test_layers.py
**Note** The first commit is from PR #416 and doesn't need to be reviewed here
------------
This commit adds a lifecycle callback that "prunes" (removes) those
primed files that already exist (with same contents and permissions) in
the base layer. This is necessary because the dependency resolver
doesn't look into the base layer when deciding dependency cutoffs (and
also to support chisel slices, which only look at the target install
dir). Some notes:
1) This first implementation only looks are regular files (no symlinks
and directories), as those are the simplest to handle and provide the
biggest size "wins". If necessary, we can address symlinks and/or
directories in follow-up work.
2) This could have been implemented during the archiving of the new
layer, where we already loop on the …
> feat: prune primed files if they exist on the base

- rockcraft/errors.py
- rockcraft/models/project.py
- rockcraft/pebble.py
- tests/unit/test_pebble.py
- tests/unit/test_project.py
Drop rockcraft's ProjectValidationError in favour of craft-application's
CraftValidationError. This lets us remove a bunch of duplicated code
related to formatting the errors and aligns us more closely with
upstream.
> refactor(project): drop ProjectValidationError

- docs/how-to/contribute-docs.rst
- docs/how-to/convert-to-pebble-layer.rst
- docs/how-to/index.rst
- docs/how-to/install-slice.rst
- docs/how-to/publish-slice.rst
- docs/how-to/rockcraft-pack-action.rst
- docs/how-to/use-chisel.rst
- docs/tutorials/chisel.rst
- docs/tutorials/index.rst
- docs/tutorials/migrate-to-chiselled-rock.rst
- docs/tutorials/node-app.rst
- docs/tutorials/pypi-package.rst
-----
I changed the doc page titles, in tutorials and how-to guides, in order to match them with their respective titles in table of contents.
> chore(docs): match doc page titles with their respective titles in toc

- requirements-dev.txt
- requirements-doc.txt
- requirements.txt
- rockcraft/models/project.py
- setup.cfg
- tests/unit/test_project.py
**Note:** The first commit bumps craft-application 1.2.0 and fixes a couple of expected messages in tests. I couldn't split this into two PRs because two of the tests (related to name validation) can only pass with the second commit.
-------------
The code refers to the 'name' message, but the bug was due to the
"error_msg_templates" in the Config: it made *every* regex validation
failure use the INVALID_NAME_MESSAGE message, even for those fields that
*aren't* the 'name'.
Since the "error_msg_templates" option is deprecated and gone in
Pydantic 2 anyway, remove it altogether and use the new
transform_pydantic_errors() hook from craft-application to preserve the
customisation of the 'name' field's message. This is necessary because
our 'name' regex is different than the 'name' regex in …
> fix: use correct error message for invalid version

- tests/unit/test_oci.py
rather than expecting scopeo to be locally installed, mock out the call in unit tests
> mock out call to `shutil.which` 

- docs/explanation/overlay-step.rst
-----
I added the missing definition for the overlay-step in explanation docs.
Note that the overlay_parameters common doc mentions `overlay-filters` field, but apparently that's a typo and it should be `overlay-files`. I fixed that in rockcraft docs, but it needs to be fixed in craft-parts docs too.
> feat(docs): add definition for overlay_step in the docs

- snap/snapcraft.yaml
-----
In preparation for a coming backward incompatible Chisel release, this PR is updating the Chisel version to a patch release that will allow for a longer grace migration period.
> chore(chisel): update Chisel to v0.8.1

- docs/how-to/code/create-slice/task.yaml
- docs/how-to/code/install-slice/task.yaml
-----
After https://github.com/canonical/chisel-releases/pull/78, the spread tests are now also failing because the building of the Chisel tool was still being done manually, from a hardcoded commit.
This PR changes the failing spread tasks such that Chisel is also installed from the snap store.
Fixes the tests for https://github.com/canonical/rockcraft/pull/455#issuecomment-1890672106.
> fix(spread): tests must also use newer Chisel

- schema/rockcraft.json
- tools/schema/schema.py
-----
This is to fix an issue in Rockcraft's schema.json, because `Permissions` needs to moved to the top scope `definitions` instead of being located inside `Part`'s definitions.
> Move Permissions definition in rockcraft schema to top scope

- .github/workflows/schema.yaml
-----
A new job was added to `schema.yaml` workflow in order to automate the validation of Rockcraft schema.
[ajv-cli](https://github.com/ajv-validator/ajv-cli) tool was used for validation. It is one of the fastest and most comprehensive JsonSchema validation tools. It was used with `--strict=false` option to allow `"format": "uri"` in the schema.
ajv-cli was able to detect validation errors similarly to JsonSchema-using IDEs like VS Code and PyCharm.
> feat: Automate schema validation in a github workflow job

- docs/how-to/code/create-slice/task.yaml
- docs/how-to/code/install-slice/task.yaml
This is a cherry-pick of a commit in `main` to cut a `1.1.2` release
> fix(spread): tests must also use newer Chisel (#456)

- rockcraft/pebble.py
- tests/spread/general/run-user-minimal/rockcraft.yaml
- tests/spread/general/run-user-minimal/task.yaml
- tests/unit/commands/test_expand_extensions.py
- tests/unit/test_project.py
Fixes #461.
This PR ensures that the `PEBBLE` default directory `/var/lib/pebble/default` always has the mode 0777.
Previously, the mode of the `PEBBLE` dir was only set to 0777 if there were services or checks specified in the `rockcraft.yaml` file. Otherwise, it used to be 0755 with user=`root` group=`root`. This meant that if Pebble was being run as some user other than root, using the `run-user` directive or some other way, the Pebble run would fail. It would fail because Pebble could not create the necessary files (socket) inside that directory. This bug is reported in issue https://github.com/canonical/rockcraft/issues/461.
-----
> fix(pebble): /var/lib/pebble/default has mode 0777

- docs/reference/rockcraft.yaml.rst
- requirements-dev.txt
- requirements-doc.txt
- requirements.txt
- rockcraft/models/project.py
- schema/rockcraft.json
- tests/integration/plugins/test_python_plugin.py
- tests/spread/general/base-devel/rockcraft.orig.yaml
- tests/spread/general/base-devel/task.yaml
- tests/spread/general/plugin-python/base-2404/rockcraft.yaml
- tests/spread/general/plugin-python/task.yaml
- tests/unit/test_project.py
This PR is a prototype/wip implementation of the same support for `devel` bases that Snapcraft has. The gist of it is: to build a noble-based rock, while noble is still in development, one can do:
```
base: ubuntu@24.04
build-base: devel
```
The PR is still in draft and has some failing integration tests but I'm putting it up for two reasons:
1) To add some spread tests to see whether we're able to build noble rocks at all (we are)
2) To have a place to discuss/argue so we can decide on the path forward and support 24.04 sooner rather than later.
So, have at it!
> feat: support ubuntu@24.04 devel rocks

- snap/snapcraft.yaml
Version 1.14.2 fixes the issue with Docker Daemon API mismatch when converting the rock to a Docker image. The previous version (1.9.0) is also over a year and a half old so it's a good idea to update anyway.
-----
> build(deps): update skopeo to 1.14.2

- .github/renovate.json5
Because we're using `requirements*.txt` files, renovate doesn't generate prefixes.
-----
> ci: group dev dependencies in renovate

- requirements-dev.txt
- requirements-doc.txt
- requirements.txt
-----
- Update base compatibility tag to ``base-v7``
- Use ``buildd`` daily for Ubuntu 24.04 (Noble) and Ubuntu devel images
- Ensure apt installs non-interactively
> build(deps): bump craft-providers to 1.23.0

- requirements-dev.txt
- requirements-doc.txt
- requirements.txt
Version 1.23.1 has a fix to parse LTS lxd versions correctly.
-----
> build(deps): bump craft-providers to 1.23.1

- rockcraft/commands/init.py
The `flask-framework` init template is not updated and contains some outdated information. Update the template.
-----
> fix: the flask-framework init template

- tests/spread/general/prune/check_layers.py
The spread test for the "layer pruning" feature worked by comparing the stats of two files if they exist in both layers. These stats - filesize, ownership and permission bits - were enough up until now because the non-pruned files differed on at least the filesize.
The recent release of libuuid1 broke this expectation: this new package has a ``libuuid.so.1.3.0`` with identical file size as the previous version, but different contents. So the pruning correctly kept the file, but the test failed.
Update the test to _also_ check the files' contents if necessary.
-----
> fix(spread): more robust check of non-pruned files

- docs/how-to/code/use-flask-extension/example/rockcraft.yaml
- docs/how-to/code/use-flask-extension/prime_example/rockcraft.yaml
- docs/how-to/code/use-flask-extension/prime_exclude_example/rockcraft.yaml
- rockcraft/application.py
- rockcraft/services/image.py
- rockcraft/services/lifecycle.py
- rockcraft/services/package.py
- schema/rockcraft.json
- tests/conftest.py
- tests/integration/services/test_lifecycle.py
- tests/testing/lifecycle.py
- tests/unit/services/test_lifecycle.py
- tests/unit/test_cli.py
- tests/unit/test_project.py
The brunt of the update is updating usages of platform/build-for to the build plan. This largely affects the image and package services, but the semantics should be unchanged because it's the same data just delivered differently.
A bit more context here is that the `feature/craft-application` branch already had a bunch of migration work done, so I just rebased that branch and created this one off it. That branch bumps craft-application to 2.3.0.
-----
> refactor: port code to latest craft-app update

- docs/how-to/code/use-flask-extension/example/rockcraft.yaml
- docs/how-to/code/use-flask-extension/prime_example/rockcraft.yaml
- docs/how-to/code/use-flask-extension/prime_exclude_example/rockcraft.yaml
- requirements-dev.txt
- requirements-doc.txt
- requirements.txt
- rockcraft/application.py
- rockcraft/cli.py
- rockcraft/models/project.py
- rockcraft/plugins/__init__.py
- rockcraft/plugins/register.py
- rockcraft/services/image.py
- rockcraft/services/lifecycle.py
- rockcraft/services/package.py
- schema/rockcraft.json
- tests/conftest.py
- tests/integration/services/test_lifecycle.py
- tests/testing/lifecycle.py
- tests/unit/commands/test_expand_extensions.py
- tests/unit/services/test_lifecycle.py
- tests/unit/test_application.py
- tests/unit/test_cli.py
- tests/unit/test_project.py
The update to the latest craft-application update was done over time in this `feature/craft-application` branch, which is now ready to be integrated back into main. Only the latest commit needs to be reviewed because we might as well update to the very new `2.4.0` - all other commits have already been reviewed in various past PRs.
> Merge craft-application update into main

- tests/spread/rockcraft/base-devel/rockcraft.orig.yaml
Those slices are currently fragile due to the ongoing time_t changes. Instead, use coreutils_bins because it has fewer dependencies (but still some) and is more stable. The purpose of the test is just to check that we can cut any slices at all for base devel anyway.
-----
> spread: don't cut dotnet slices unnecessarily

- docs/reference/rockcraft.yaml.rst
- rockcraft/extensions/gunicorn.py
- tests/spread/rockcraft/extension-flask/task.yaml
- tests/unit/extensions/test_gunicorn.py
-----
We have now tested the extension with the web team and they are happy with. This means we're ready to move the flask-framework extension to be stable.
> remove experimental flag for flask-framework extension

- rockcraft/pebble.py
- tests/spread/rockcraft/base-devel/task.yaml
- tests/unit/test_application.py
- tests/unit/test_pebble.py
-----
After discussion with the Starcraft team, it has been agreed on to move the `pebble` binary to `/usr/bin` instead of `/.rock/bin` for 24.04, since we're quite sure that the `/usr/bin` dir won't change for 24.04.
This PR builds over the previous PR https://github.com/canonical/rockcraft/pull/528 but replaces the pebble path for 24.04 and onwards to `/usr/bin`, and change .
PR https://github.com/canonical/rockcraft/pull/528
Aside from spread tests, this is a manual test using the Hello World rock with build-base of 24.04 to confirm the path of pebble binary.
Rock:
```yaml
name: chiselled-hello
summary: Hello world from Chisel slices
description: A "bare" rock containing the "hello" package binaries from Chisel slices.
license: Apache-2.0
version: "latest"
base: bare
build_base: …
```
> fix: change pebble dir in 24.04 from /.rock/bin to /usr/bin

- snap/snapcraft.yaml
Some archs don't have wheels for some of the dependencies (like pygit2).
-----
Tested using remote-build for arm64, armhf, ppc64el, riscv64, s390x
> build: fix snap build in non-amd64 archs

- rockcraft/pebble.py
- snap/snapcraft.yaml
- tests/spread/rockcraft/base-devel/task.yaml
- tests/unit/test_application.py
- tests/unit/test_pebble.py
> chore: merge 'hotfix/1.3' back into 'main'

- tests/spread/rockcraft/base-devel/rockcraft.orig.yaml
- tests/spread/rockcraft/chisel/rockcraft.yaml
The issue is that chisel releases necessarily lag behind mainline Ubuntu development, as each new series needs to be manually added to the chisel-releases repo. The case in point here is that 'devel' has just started to mean "Ubuntu 24.10", but this version is not available in chisel-releases yet.
So we drop the use of slices in 'devel' tests, which should be fine because the point is to see whether the *rest* of Rockcraft's execution works.
-----
> fix(tests): don't use chisel slices in 'devel' bases

- docs/how-to/code/convert-to-pebble-layer/task.yaml
- docs/how-to/code/install-slice/task.yaml
- docs/how-to/code/migrate-to-chiselled-rock/task.yaml
- docs/tutorials/code/chisel/task.yaml
- docs/tutorials/code/hello-world/task.yaml
- docs/tutorials/code/node-app/task.yaml
- docs/tutorials/code/pyfiglet/task.yaml
- snap/snapcraft.yaml
- tests/spread/foreign/big/task.yaml
- tests/spread/general/extension-django/task.yaml
- tests/spread/large/repo-overlay/task.yaml
- tests/spread/rockcraft/bare-base/task.yaml
- tests/spread/rockcraft/base-devel/task.yaml
- tests/spread/rockcraft/chisel/task.yaml
- tests/spread/rockcraft/craftctl/task.yaml
- tests/spread/rockcraft/entrypoint-service/task.yaml
- tests/spread/rockcraft/environment/task.yaml
- tests/spread/rockcraft/extension-flask/task.yaml
- tests/spread/rockcraft/health-checks/task.yaml
- tests/spread/rockcraft/init/task.yaml
- tests/spread/rockcraft/plugin-python-3.6/task.yaml
- tests/spread/rockcraft/plugin-python/task.yaml
- tests/spread/rockcraft/prune/check_layers.py
- tests/spread/rockcraft/repo-bare-base/task.yaml
- tests/spread/rockcraft/repo-ubuntu-base/task.yaml
- tests/spread/rockcraft/run-user-minimal/task.yaml
- tests/spread/rockcraft/run-user/task.yaml
- tests/spread/rockcraft/usrmerge-file-collision/task.yaml
- tests/spread/rockcraft/usrmerge/task.yaml
skopeo was already part of our UI because a lot of our tutorials referenced /snap/rockcraft/current/bin/skopeo directly, and this has been requested by users.
-----
> feat(snap): expose skopeo as rockcraft.skopeo

- docs/reference/plugins.rst
- requirements-dev.txt
- requirements-doc.txt
- requirements.txt
Version 1.31.0 brings in a new set of plugin docs.
-----
> build(deps): bump craft-parts to 1.31.0

- spread.yaml
-----
Fedora 37 workers don't seem to be working anymore.
This PR bump spread's fedora worker version from 37 to 39.
> Bump spread's fedora worker version from 37 to 39

- .readthedocs.yaml
- docs/conf.py
This PR contains two commits:
* build(docs): fetch tags in readthedocs builds 
Readthedocs builds don't fetch tags when cloning the repo. This is a problem
for us because Rockcraft's version comes from the tag (via setuptools-scm),
so do a fetch of the tags as a post-checkout step.
* docs: use "dev" for non-release builds
The bug is this: If a build is done off of (say) 'main', the version coming
from 'git describe' will be something like 1.32.2.postXXXX. We previously
dropped the ".post*" suffix because it confused the spellchecker but that
just leaves the misleading "1.32.2" string. It's misleading because that's
an actual released version that does *not* contain a lot of the content
in 'main'.
So just use "dev" instead, to make it extra explicit that the docs refer
to an unreleased …
> docs: fix incorrect version in documentation

- docs/reference/rockcraft.yaml.rst
- rockcraft/commands/init.py
- rockcraft/models/project.py
- schema/rockcraft.json
- tests/unit/test_project.py
-----
`license` becomes an optional field, and as a result, it no longer shows up in the templated `rockcraft.yaml` file, for any profile.
> feat: make 'license' an optional field

- docs/reference/plugins.rst
- requirements-dev.txt
- requirements-doc.txt
- requirements.txt
- tests/unit/test_cli.py
Use the `rockcraft` branch from the `craft-parts` and `craft-application` repos.
> chore: point to temporary build dependencies

- requirements-dev.txt
- requirements-doc.txt
- requirements.txt
- rockcraft/models/project.py
- tests/spread/rockcraft/invalid-name/task.yaml
- tests/unit/test_project.py
The rule is this: in validators, always raise the types that Pydantic expects (ValueErrors, AssertionErrors, TypeError, and subclasses of these). This allows Pydantic to capture all errors and group them into a single ValidationError, which we can then convert into a single CraftValidationError in from_yaml_data(). This provides a more uniform UI for the reporting of validation errors on the project.
-----
> fix: don't raise CraftValidationErrors in validators

- rockcraft/application.py
- rockcraft/commands/extensions.py
- rockcraft/models/project.py
- tests/unit/commands/test_expand_extensions.py
- tests/unit/testing/extensions.py
- fix: fix report of validation errors in expand-extensions
- chore: set base doc url and reference slug
> multiple error-related fixes

- docs/conf.py
> fix: 404 docs page

- rockcraft/commands/init.py
- tests/spread/rockcraft/init/task.yaml
- tests/unit/test_cli.py
- Snapcraft uses message, progress hides the docs url as it is "uni-line"
- Use a similar message to what is done in Snapcraft
- Improve the test for initializing flask-framework
- Use the correct documentation slug
-----
> fix: switch from progress to message for init

- rockcraft/extensions/gunicorn.py
- tests/unit/extensions/test_gunicorn.py
> fix(flask): handle SyntaxErrors when parsing app.py

- rockcraft/commands/init.py
- tests/unit/test_cli.py
runtime-slices and runtime-debs aren't parts that the extension is aware of, so prefixing them with 'flask-framework/' is misleading and a conceptual error.
-----
> fix(flask): drop 'flask-framework/' prefix in template

- docs/conf.py
- requirements-dev.txt
- requirements-doc.txt
- requirements.txt
Now that those libs have been released we can use proper version ids again.
Fixes #619
> build(deps): use proper versions for craft- libs

- requirements-dev.txt
- requirements-doc.txt
- requirements.txt
- rockcraft/models/project.py
- schema/rockcraft.json
- setup.cfg
- tests/conftest.py
- tests/unit/commands/test_expand_extensions.py
- tests/unit/test_project.py
- tools/schema/schema.py
-----
This is a test PR for https://github.com/canonical/craft-application/pull/326, to see if the default BuildPlanner will work for rockcraft.
There are a few pre-requisite commits to be compatible with the latest craft-application.
I wasn't able to get pydantic to use [this](https://github.com/canonical/craft-application/pull/326/files#diff-d49e733a1e99a8cc3fe98cb7d956b735159c60342405692603fe5fcf8a970edaR111) upstream validator but everything else seems to be in working order.
(CRAFT-2824)
> refactor: use default BuildPlanner

- requirements-dev.txt
- requirements-doc.txt
- requirements.txt
- rockcraft/application.py
- rockcraft/commands/init.py
- rockcraft/extensions/gunicorn.py
- tests/unit/test_cli.py
- tools/schema/schema.py
This updates the links used for errors, but also for init templates.
Example with a fake version `9.9.9`:
```
❯ rockcraft init --profile=flask-framework
Created 'rockcraft.yaml'.
Go to https://documentation.ubuntu.com/rockcraft/en/9.9.9/reference/extensions/flask-framework to read more about the 'flask-framework' profile.
❯ cat rockcraft.yaml 
name: rockcraft
base: ubuntu@22.04 # the base environment for this Flask application
...
```
> feat: use versioned form of doc urls

- tests/spread/rockcraft/chisel/task.yaml
-----
Pebble `enter` no longer supports using `-v` with the `exec` command. This PR fixes a spread test that is failing because of that.
> fix(spread): Pebble no longer supports -v with exec

- docs/tutorial/flask.rst
A small PR to fix a filename in the flask Tutorial.
-----
> fix(docs/tutorial/flask.rst): fixed misspelt filename in tutorial

- docs/Makefile
This PR includes several fixes for the language tests in our docs/Makefile:
- Fixed woke utility skipping .*ignore files. This appears to be a bug in the utility. I'll raise this issue with the maintainer.
- Disabled default woke configuration and exclusively test ours in canonical/Inclusive-naming.
- Enabled error exit status. The Tests action will now show if there are language issues.
-----
> Fix docs build languange tests

- spread.yaml
- tests/integration/services/test_lifecycle.py
These are two fixes done in `feature/pydantic-2`, cherry-picked here to unbreak `main`
> cherry pick fixes to main

- spread.yaml
This serves two purposes:
a) It un-breaks `main` as `5.21/candidate` has the fixes for the regressions
when mounting the overlay filesystems;
b) It lets the spread tests act as a line of defense against further LTS
regressions, without being too exposed to breakage by using something like
`latest/edge`.
-----
> tests(spread): use LXD from `5.21/candidate`

- .readthedocs.yaml
- docs/tutorial/django.rst
- docs/tutorial/flask.rst
The readthedocs build started sporadically failing; what I *think* is happening is that the latest tag (1.5.3) is far enough from the HEAD of main (over 50 commits) that the previous command of fetching the tags was no longer sufficient to have "git describe" be able to reach the tag.
-----
> chore: unshallow clone used in readthedocs

- docs/tutorial/flask.rst
I discussed with tutorial with Daniele, who expressed some concerns about the way the tutorial was written. Emphasizing the user doing something ("you do X, then you do Y, ...") gives the impression of a how-to guide. A tutorial is more about doing something together with the user as a learning experience.
Therefore, I changed some of the language from "you" to "we" to frame the experience as more of a tutorial. We're doing this together with the user so that they can learn how to build a rock for a Flask app. 
I left some instances of "you" alone where I thought it was appropriate to include.
-----
> docs: use more inclusive language in flask tutorial

- requirements-dev.txt
- requirements-doc.txt
- requirements.txt
- rockcraft/models/project.py
- setup.cfg
The semantics are the same; the goal is to have a single source of build plans that is used both by Rockcraft and by whatever other code (e.g. remote builds) might need it.
Fixes #698
-----
> refactor: use craft-platform for the build plans

- .github/workflows/tests.yaml
- docs/conf.py
- docs/reference/plugins.rst
- docs/reference/plugins/_python_common.rst
- docs/reference/plugins/poetry_plugin.rst
- docs/reference/plugins/python_plugin.rst
- rockcraft/plugins/poetry_plugin.py
- rockcraft/plugins/python_common.py
- rockcraft/plugins/register.py
- rockcraft/services/lifecycle.py
- tests/integration/plugins/python_source/pyproject.toml
- tests/integration/plugins/test_python_plugin.py
- tests/spread/rockcraft/plugin-poetry/rockcraft.yaml
- tests/spread/rockcraft/plugin-poetry/src/pyproject.toml
- tests/spread/rockcraft/plugin-poetry/src/test_poetry/__main__.py
- tests/spread/rockcraft/plugin-poetry/task.yaml
- tests/unit/services/test_lifecycle.py
The plugin has the same behavior and restrictions as the Python plugin with regards to base-dependent behavior, symlink handling, sitecustomize, etc.
Therefore, this common behavior is extracted into a new "python_common" module, used by both plugins. This approach is also taken for the reference docs - the requirement of staging a Python interpreter is the same for both plugins.
Fixes #701
-----
> feat: add Rockcraft-specific Poetry plugin

- docs/.wordlist.txt
- docs/tutorial/django.rst
- docs/tutorial/flask.rst
- docs/tutorial/node-app.rst
In compliance with the Ubuntu and reST style guides.
-----
In compliance with the Ubuntu and reST style guides.
> docs: use correct keypress style, fix markup

- rockcraft/oci.py
- rockcraft/pebble.py
- rockcraft/services/package.py
- tests/spread/rockcraft/bare-base/rockcraft.orig.yaml
- tests/spread/rockcraft/bare-base/task.yaml
- tests/unit/test_oci.py
If the PATH is empty, Pebble will be default use the standard Ubuntu value
of "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" (see [0]).
Follow this lead and set this value on the image's PATH.
This PATH setting on the image itself has no bearing on most cases, as the
PATH that prevails is the one defined by Pebble and its services, but an
empty (or unset) PATH is a potential security issue in cases where the pebble
entrypoint is bypassed.
0: https://github.com/canonical/pebble/blob/master/internals/overlord/cmdstate/request.go#L91
Fixes #711
> fix: set PATH on bare-based rocks

- .github/workflows/tests.yaml
- Makefile
- requirements-dev.txt
- setup.cfg
Both of these have been replaced with ruff.
-----
> chore: remove flake8 and pydocstyle

- rockcraft/models/project.py
pyright complains about assigning str | None type in constructor to a str type.
Exception can not be None, strerror is declared as str. We can do a str() when assigning msg, but this seems a pyright issue, so probably it is best to suppress the type check.
Apparently the declaration does not match the actual returned type: https://github.com/python/typeshed/issues/9864, so using `or "unknown"` as suggested.
-----
> lint: suppress linter warning

- rockcraft/oci.py
- rockcraft/services/package.py
- tests/spread/rockcraft/run-user-minimal/task.yaml
- tests/spread/rockcraft/run-user/task.yaml
- tests/unit/test_oci.py
-----
This addresses Issue #659 by setting the OCI image's .Config.User to userid instead of the username.
> Change .Config.User from username to userid

- snap/local/craft.git
- snap/snapcraft.yaml
- tests/spread/rockcraft/craftgit/rockcraft.yaml
- tests/spread/rockcraft/craftgit/task.yaml
This PR adds stages `git` in the `rockcraft` snap package, to enable `git`-based operations for `craft` libraries.
(CRAFT-3548)
> feat(snap): add git as craft.git to rockcraft

- rockcraft/models/project.py
- tests/spread/rockcraft/expand-extensions/task.yaml
- tests/unit/test_project.py
The use-case that this enables is packing the output of 'expand-extensions'. Previously, this would fail because the expanded yaml contains the 'pebble' part that Rockcraft adds, and then Rockcraft itself would complain that the project already has a part called 'pebble'.
This commit makes Rockcraft accept an existing part called 'pebble' if the contents of said part are the same as the one we would add.
Fixes #749
-----
> fix: accept a 'pebble' part if its the same as ours

- snap/snapcraft.yaml
Looks like the combination of core24 + riscv64 is not supported by the store currently, which means that 'edge' hasn't been following 'main' since we updated the snap to core24.
-----
> build(snap): drop 'riscv64' for now

- snap/snapcraft.yaml
libgpgme11 and libbtrfs0 don't exist on armhf, so we must use the 't64' packages that exist in all archs.
-----
> build(snap): update stage-packages for armhf

- docs/reference/index.rst
- docs/reference/remote-build.rst
- docs/reference/remote-builds.rst
This is loosely inspired on the existing docs for Snapcraft, but with a different set of restrictions and no concerns about 'legacy' versus 'new' builders.
Note that this is complementary to the command reference that is autogenerated from the Python code.
Fixes #597
-----
> docs: reference docs for remote builds

- docs/how-to/code/build-docs/task.yaml
- docs/tutorial/code/fastapi/requirements.txt
- pyproject.toml
- schema/rockcraft.json
- tests/unit/test_project.py
- uv.lock
> Update deps, fix build on main

- .github/workflows/qa.yaml
- .github/workflows/release-publish.yaml
- .readthedocs.yaml
- Makefile
- docs/reference/plugins.rst
- schema/rockcraft.json
- tests/unit/test_oci.py
- uv.lock
> Update craft parts, minor build and ci fixes

- tests/spread/rockcraft/plugin-jlink/bare-build-2404/rockcraft.yaml
- tests/spread/rockcraft/plugin-jlink/base-2404/helloworld/pom.xml
- tests/spread/rockcraft/plugin-jlink/base-2404/helloworld/src/main/java/com/yourcompany/helloworld/App.java
- tests/spread/rockcraft/plugin-jlink/base-2404/helloworld/src/test/java/com/yourcompany/helloworld/AppTest.java
- tests/spread/rockcraft/plugin-jlink/base-2404/rockcraft.yaml
- tests/spread/rockcraft/plugin-jlink/helloworld/pom.xml
- tests/spread/rockcraft/plugin-jlink/helloworld/src/main/java/helloworld/App.java
- tests/spread/rockcraft/plugin-jlink/helloworld/src/test/java/helloworld/AppTest.java
- tests/spread/rockcraft/plugin-jlink/parts.yaml
- tests/spread/rockcraft/plugin-jlink/task.yaml
This PR adds JLink plugin smoke test to rockcraft.
The PR is draft until craft-parts release.
Commit 42b68ddaa80d74b3bda1c87c959537a13ea723d0 should be removed from the final PR.
---
> Validate jlink plugin

- .readthedocs.yaml
This should force Sphinx to use the dirhtml builder, which will enforce clean
URLs instead of .html
---
> docs(build): switch to extensionless URLs

- snap/snapcraft.yaml
The `astral-uv` snap on `armhf` needs to be updated/fixed. Until then, we need to stop using it.
---
> build(snap): disable armhf

- rockcraft/extensions/go.py
- tests/unit/extensions/test_go.py
---
This adds the required binaries for the go extension when the base is bare
> fix: add missing binaries to the go-framework extension for bare base

- rockcraft/models/project.py
- tests/unit/test_project.py
---
Added `org.opencontainers.image.description` OCI annotation to all rocks. This annotation uses a combination of `summary` + `description` fields from `rockcraft.yaml` file, following this format:
```
<summary>
<description>
```
The annotation is addded to the `Config.Labels` field in Docker.
---
Example for the `hello-world` rock:
Input:
`docker image inspect hello:latest | jq -r .[0].Config.Labels`
Output:
> feat: add org.opencontainers.image.description to rocks

- rockcraft/models/project.py
- tests/unit/test_project.py
---
Sanitize the `summary` field before constructing the `"org.opencontainers.image.description"` annotation, such that we avoid causes where the `summary` itself already includes multiple consecutive `\n` chars, thus breaking the existing convention of a double-newline-delimiter for the annotation.
> fix: sanitize summary for OCI annotation

- docs/tutorial/code/expressjs/task.yaml
- docs/tutorial/code/node-app/rockcraft.yaml
- rockcraft/extensions/expressjs.py
- tests/spread/rockcraft/extension-expressjs/task.yaml
- tests/unit/extensions/test_expressjs.py
I should note for the rustaceans in the crowd that this refers to [libuv](https://github.com/libuv/libuv), which node uses to do async io
> chore: set UV_USE_IO_URING=0 on npm builds

- docs/reference/plugins.rst
- pyproject.toml
- rockcraft/extensions/_utils.py
- schema/rockcraft.json
- tests/spread/foreign/big/rockcraft.yaml
- tests/spread/rockcraft/destructive/rockcraft.yaml
- uv.lock
The craft-parts update brings in the 'cargo-use' plugin, and the craft-platforms
update allows us to use "ubuntu:22.04" deprecated notation again.
> build(deps): update craft-parts and craft-platforms

- Makefile
- rockcraft/oci.py
- rockcraft/services/package.py
- tests/integration/services/test_package.py
- tests/integration/test_oci.py
- tests/unit/test_oci.py
- uv.lock
---
This PR make `rockcraft` add the field `mediaType` in the image manifest, which is missing in the default manifest created by `umoci`.
> feat(oci): inject mediatype in manifest

- docs/conf.py
- pyproject.toml
- rockcraft/templates/test/spread.yaml.j2
- tests/spread/rockcraft/extension-flask-async/requirements.txt
- tests/unit/test_cli.py
- uv.lock
❯ uv lock --upgrade
Resolved 205 packages in 4.46s
Updated astroid v3.3.9 -> v3.3.10
Updated cachecontrol v0.14.2 -> v0.14.3
Updated charset-normalizer v3.4.1 -> v3.4.2
Updated click v8.1.8 -> v8.2.1
Updated coverage v7.8.0 -> v7.8.2
Updated craft-application v5.2.0 -> v5.3.0
Updated craft-parts v2.9.1 -> v2.10.0
Updated craft-platforms v0.8.0 -> v0.9.0
Updated craft-providers v2.2.0 -> v2.3.0
Updated cryptography v44.0.2 -> v45.0.3
Updated exceptiongroup v1.2.2 -> v1.3.0
Updated pbs-installer v2025.4.9 -> v2025.5.17
Updated platformdirs v4.3.7 -> v4.3.8
Updated pluggy v1.5.0 -> v1.6.0
Updated poetry v2.1.2 -> v2.1.3
Updated poetry-core v2.1.2 -> v2.1.3
Updated protobuf v6.30.2 -> v6.31.1
Updated pydantic v2.11.3 -> v2.11.5
Updated pydantic-core v2.33.1 -> v2.33.2
Updated pylint v3.3.6 -> …
> build(deps): update dependencies

- docs/tutorial/code/django/task.yaml
- docs/tutorial/code/expressjs/task.yaml
- docs/tutorial/code/fastapi/task.yaml
- docs/tutorial/code/flask/task.yaml
- docs/tutorial/code/go/task.yaml
- docs/tutorial/code/spring-boot/task.yaml
- docs/tutorial/django.rst
- docs/tutorial/expressjs.rst
- docs/tutorial/fastapi.rst
- docs/tutorial/flask.rst
- docs/tutorial/go.rst
- docs/tutorial/index.rst
- docs/tutorial/springboot.rst
I ran `make lint` and received errors on files this PR doesn't touch.
---
Updates to the tutorials based on feedback in UX sessions:
1. When copying the skopeo command for the chiseled hello world rock. The user missed the hint to change the name in the project file to `0.1-chisel`, resulting in a error.
2. File headers could be added to file excerpts (app.py) [External example](https://www.digitalocean.com/community/tutorials/how-to-make-a-web-application-using-flask-in-python-3)
3. Clarification may be needed on what the skopeo command is doing. Maybe we could also mention about how Docker requires rocks (or images in general) to be imported into the daemon since they cannot be executed directly like an executable.
In addition, two corrections to the Express and Spring Boot tutorials: …
> docs: Incorporate UX feedback into 12-factor tutorials

- docs/reference/extensions/django-framework.rst
- docs/reference/extensions/flask-framework.rst
---
This PR adds documentation about Gunicorn metrics for Django and Flask extensions. It also explains how to push app metrics to the StatsD exporter.
> docs: cover statsd metrics in extensions

- tests/integration/test_oci.py
---
One of the OCI tests was leaving behind test files in the main project directory after running. This PR just makes those test files live in a temp directory instead.
> test: don't leave behind test files

- requirements-noble.txt
- snap/snapcraft.yaml
---
Export hashes with uv, correcting a small oversight of https://github.com/canonical/rockcraft/pull/977.
> fix: export deps with hashes
