.github/workflows/snap.yaml, .gitignore, snap/snapcraft.yaml
Signed-off-by: Sergio Schvezov <sergio.schvezov@canonical.com>
-------
-----
=> snap: introduce initial snap packaging (CRAFT-578)

requirements-dev.txt, requirements-doc.txt, requirements.txt, rockcraft/cli.py, rockcraft/lifecycle.py, rockcraft/oci.py, rockcraft/parts.py, rockcraft/providers/_logs.py, rockcraft/ui.py, setup.cfg, tests/unit/test_cli.py, tools/freeze-requirements.sh
Update craft-cli to 0.4, pause the emitter when re-executing rockcraft
in instance and redirect output streams.
Output should now be more organized and descriptive:
```
$ rockcraft pack
Launching instance...                                                                                                                                                                     
Retrieved base ubuntu:20.04                                                                                                                                                               
Extracted ubuntu:20.04                                                                                                                                                                    
Executed: pull hello …
```
=> requirements: unpin and update craft-cli 

requirements-dev.txt, requirements-doc.txt, requirements.txt, rockcraft/providers/_buildd.py, setup.cfg
If a new injection is required it should also be performed on
instance warm-up. Note that snaps that are already installed won't
be reinstalled.
-----
=> providers: override instance warmup

rockcraft/commands/lifecycle.py
It packs a ROCK, not a snap.
-----
=> cli: Fix description of "rockcraft pack"

README.rst
Add some notes on the requirements for running spread tests (git
submodules, a rockcraft snap, and snapd-spread access).
-----
=> spread: add some basic docs on running spread

requirements-dev.txt, requirements-doc.txt, requirements.txt
-----
Unblocks https://github.com/canonical/rockcraft/pull/82
=> requirements: update craft-providers to 1.5.0

docs/_static/css/custom.css
-----
Change the documentation's body font family to "ubuntu"
=> docs: change fonts to Ubuntu family

docs/reference.rst
-----
First draft of documenting rockcraft commands.
Resolves https://github.com/canonical/rockcraft/issues/101
=> docs: add commands

docs/reference.rst
=> fix: docs inline code block was misplaced

snap/snapcraft.yaml
=> fix: pin the commit of the bundled chisel

Makefile, docs/_static/css/custom.css, docs/conf.py, docs/explanation.rst, docs/how-to/build-docs.rst, docs/how-to/get-started.rst, docs/how-to/index.rst, docs/index.rst, docs/reference.rst, docs/tutorials.rst, requirements-doc.txt
Made some documentation improvements
- [* ] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
-----
=> Docs improvements

.github/workflows/tests.yaml, docs/how-to/build-docs.rst, docs/how-to/index.rst
Since we're picking up speed with the docs we may as well enable the docs linter.
-----
=> ci: run sphinx-lint on CI too

requirements-dev.txt, requirements.txt, tests/spread/general/big/rockcraft.yaml, tests/spread/general/big/task.yaml
=> Craft 1415 rockcraft permissions

rockcraft/project.py, snap/snapcraft.yaml, tests/unit/test_project.py
=> Cleanup the parts for Chisel and Pebble

rockcraft/project.py, tests/spread/general/big/task.yaml, tests/unit/test_project.py
=> parts: compile Pebble as a static binary

CONTRIBUTING.rst
Create a file containing guidelines for contributing code to Rockcraft.
-----
=> docs: add contributing file

docs/how-to/create-slice.rst, docs/how-to/index.rst
=> docs: add explanation about creating a slice

docs/how-to/index.rst, docs/how-to/install-slice.rst
=> docs: add explanation about installing a slice with rockcraft

docs/how-to/index.rst, docs/how-to/publish-slice.rst
=> docs: add explanation about publishing a slice

rockcraft/cli.py, rockcraft/lifecycle.py, rockcraft/parts.py, tests/unit/test_lifecycle.py, tests/unit/test_parts.py
The clean command can now clean specific parts inside the managed environment.
-----
=> parts: allow cleaning specific parts

spread.yaml
Update external testing tools submodule.
-----
=> tools: update external testing tools

.github/workflows/tests.yaml, Makefile, tests/spread/general/big/task.yaml, tests/spread/general/chisel/task.yaml, tools/freeze-requirements.sh
-----
Add new linter for shellcheck and spread-shellcheck to the github workflow.
Includes some minor fixes to be shellcheck-compliant.
=> lint: add shellcheck and spread-shellcheck linters

Makefile, spread.yaml
=> lint: run shellcheck on spread.yaml

requirements-jammy.txt
=> deps: add requirements-jammy.txt with python-apt from Ubuntu jammy

rockcraft/cli.py, rockcraft/lifecycle.py, rockcraft/parts.py, rockcraft/plugins/__init__.py, rockcraft/plugins/python_plugin.py, rockcraft/plugins/register.py, tests/integration/plugins/python_source/hello/__main__.py, tests/integration/plugins/python_source/setup.py, tests/integration/plugins/test_python_plugin.py, tests/integration/test_oci.py, tests/spread/general/plugin-python/bare-build-2004/rockcraft.yaml, tests/spread/general/plugin-python/bare-build-2204/rockcraft.yaml, tests/spread/general/plugin-python/base-2004/rockcraft.yaml, tests/spread/general/plugin-python/base-2204/rockcraft.yaml, tests/spread/general/plugin-python/parts.yaml, tests/spread/general/plugin-python/src/hello/__main__.py, tests/spread/general/plugin-python/src/setup.py, tests/spread/general/plugin-python/task.yaml, tests/unit/plugins/test_python_plugin.py, tests/unit/test_lifecycle.py, tests/unit/test_parts.py
The specialized plugin has logic to support bare and ubuntu bases.
The diff is quite big but most of that is from test updates.
(CRAFT-1664)
=> plugins: add rockcraft specific python plugin

spread.yaml, tests/spread/general/configure-hook/task.yaml, tests/spread/general/remove-hook/task.yaml
=> spread: increase the number of workers

rockcraft/commands/lifecycle.py, rockcraft/lifecycle.py, tests/spread/general/destructive/rockcraft.yaml, tests/spread/general/destructive/task.yaml, tests/unit/test_cli.py, tests/unit/test_lifecycle.py
Just like in Snapcraft or Charmcraft, this flag builds the ROCK on the host.
-----
=> cli: add --destructive-mode flag

snap/snapcraft.yaml
=> snap: update chisel to latest main

docs/Makefile, docs/conf.py, docs/explanation.rst, docs/how-to/create-slice.rst, docs/how-to/install-slice.rst, docs/reference.rst
=> docs: fix markup

spread.yaml
-----
Test to install docker after LXD.
=> tests: install docker after lxd

docs/explanation/chisel.rst, docs/explanation/index.rst, docs/explanation/rockcraft.rst, docs/index.rst
=> docs: create separate chisel documentation

pyproject.toml, requirements-dev.txt, setup.cfg, tests/unit/conftest.py
-----
Stricter configuration that causes many failures has been commented out for the timebeing.
=> tools: use starbase configuration for mypy

.github/ISSUE_TEMPLATE/bug.yaml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/task.yaml, .github/workflows/issues.yaml
=> github: JIRA integration for issues

docs/explanation/chisel.rst, docs/explanation/index.rst, docs/explanation/rockcraft.rst, docs/explanation/rocks.rst, docs/how-to/use-chisel.rst, docs/index.rst, docs/links.txt, docs/reference.rst, docs/tutorials/chisel.rst
=> docs: split rock explanation into its own document

requirements-dev.txt, requirements-doc.txt, requirements.txt
=> dependencies: update craft-cli to 2.0.0

requirements-dev.txt, requirements-doc.txt, requirements.txt, rockcraft/parts.py, rockcraft/project.py, tests/unit/test_project.py
=> project: block overlay usage with "bare" bases

docs/how-to/convert-to-pebble-layer.rst
This fix permit to solve the issue with linkcheck on the convert-to-pebble-layer.rst.
Signed_Off_By: Samir Akarioh <samir.akarioh@canonical.com>
-----
=> docs: fix url of rockcraft format

docs/how-to/convert-to-pebble-layer.rst
=> docs: remove fragment from link for linting

requirements-dev.txt, requirements-doc.txt, requirements.txt, tests/spread/general/overlay-logs/rockcraft.yaml, tests/spread/general/overlay-logs/task.yaml
=> requirements: bump craft-cli to fix logging in overlay

docs/tutorials/code/hello-world/rockcraft.yaml, docs/tutorials/hello-world.rst
This PR add little explanation about the rockcraft.yaml file on the hello world tutorial
Signed_Off_Based: Samir Akarioh <samir.akarioh@canonical.com>
-----
=> docs: Add explanation on the Hello-world tutorial

docs/explanation/overlay-step.rst
-----
https://canonical-rockcraft--322.com.readthedocs.build/en/322/
=> docs: enable inclusion of overlay document

.github/renovate.json5
I messed this up a while back and Renovate's linter didn't catch my mistake, so I'm here to fix it.
-----
=> ci: fix renovate scheduling

tests/integration/plugins/test_python_plugin.py
=> type: fix pyright possibly-unbound error

.github/workflows/snap.yaml
=> fix(ci): filter out feature/ from git branch for snap channel branch

rockcraft/pebble.py, tests/unit/commands/test_expand_extensions.py, tests/unit/test_project.py
=> chore: update pebble to latest/stable

docs/tutorials/code/hello-world/rockcraft.yaml
Some lines have trailing white spaces and I've removed them, tools like yamllint complain.
-----
=> chore(lint): Remove trailing whitespace

requirements-dev.txt, requirements-doc.txt, requirements.txt, rockcraft/application.py, tests/spread/general/build-secrets/rockcraft.yaml, tests/spread/general/build-secrets/task.yaml
=> feat: enable build-secrets

docs/conf.py, docs/reference/code/example/rockcraft.yaml, docs/reference/code/example/task.yaml, docs/reference/rockcraft.yaml.rst, docs/tutorials/code/node-app/task.yaml, spread.yaml
Put the example code in a spread test, to ensure that we can always build the example we give in the docs.
Fixes #399
-----
=> fix(docs): make sure we can build the example rockcraft.yaml

snap/snapcraft.yaml
=> fix: dynamic grade to allow to release to stable

docs/how-to/code/get-started/task.yaml, docs/tutorials/code/chisel/task.yaml, docs/tutorials/code/hello-world/task.yaml, docs/tutorials/code/migrate-to-chiselled-rock/task.yaml, docs/tutorials/code/node-app/task.yaml
=> fix(docs): drop "--edge" from rockcraft install instructions

.readthedocs.yaml
=> chore(docs): fix version in readthedocs build

docs/index.rst
-----
Adding more prominent links to Discourse on ROCKS home page.
=> Add ROCKS discourse link to home page

docs/reference/index.rst, docs/reference/rock_parts/toc.rst, docs/reference/rockcraft.yaml.rst
-----
Move part_properties under rockcraft.yaml in Reference's toctree.
=> move part_properties under rockcraft.yaml in Reference's toctree

docs/.wordlist.txt, docs/reference/index.rst, docs/reference/plugins.rst, docs/reference/plugins/python_plugin.rst, docs/reference/plugins/rust_plugin.rst, requirements-dev.txt, requirements-doc.txt, requirements.txt
These are brought in unchanged from craft-parts.
Fixes #434
-----
=> docs: add python and rust plugin ref

.github/workflows/spread-large.yaml, .github/workflows/spread.yaml
-----
A direct copy of: https://github.com/snapcore/snapcraft/blob/main/.github/workflows/spread.yml#L117
=> ci: always discard spread workers

snap/snapcraft.yaml
=> chore(merge): merge 'hotfix/1.2' back to 'main'

.github/renovate.json5, .github/workflows/spread-large.yaml, .github/workflows/spread.yaml, snap/snapcraft.yaml
-----
Merge main into feature/12f branch, to keep it up to date and ensure edge/12f channel stays open
=> chore: Merge main into Feature/12f

requirements-dev.txt, requirements-doc.txt, requirements.txt, rockcraft/application.py, rockcraft/cli.py, rockcraft/models/project.py, rockcraft/plugins/__init__.py, rockcraft/plugins/register.py, rockcraft/services/lifecycle.py, schema/rockcraft.json, tests/conftest.py, tests/integration/services/test_lifecycle.py, tests/unit/commands/test_expand_extensions.py, tests/unit/services/test_lifecycle.py, tests/unit/test_application.py, tests/unit/test_project.py
Three separate commits, for the BuildPlanner stuff and pruning some code that is no longer necessary.
=> Update to craft-application@main

requirements-dev.txt, requirements-doc.txt, requirements.txt, rockcraft/services/lifecycle.py, tests/unit/services/test_lifecycle.py
=> chore(merge): merge 'hotfix/1.2' back into 'main'

rockcraft/commands/init.py, rockcraft/extensions/gunicorn.py, tests/unit/extensions/test_gunicorn.py
-----
Makes it an error for the any gunicorn based extension not to define a `base`, `build-base` and `platforms` key
=> fix(flask): don't enforce definition of base, build-base and platforms

rockcraft/models/project.py, schema/rockcraft.json, tests/spread/rockcraft/plugin-python/base-2404/rockcraft.yaml, tests/unit/test_project.py
=> feat(project): ubuntu@24.04 is no longer "devel"

requirements-dev.txt, requirements-doc.txt, requirements.txt, rockcraft/models/project.py, tests/integration/plugins/test_python_plugin.py, tests/unit/services/test_lifecycle.py, tests/unit/test_project.py
=> build(deps): bump craft-application to 2.7.0

.github/workflows/spread-large.yaml, .github/workflows/spread.yaml
=> ci: run spread tests on 'spread-installed' runners

rockcraft/application.py, rockcraft/models/project.py, tests/conftest.py, tests/integration/services/test_lifecycle.py, tests/integration/test_oci.py, tests/spread/rockcraft/init/task.yaml, tests/unit/test_project.py
=> fix: enable overlays in _enable_craft_parts_features()

rockcraft/commands/init.py, tests/unit/test_cli.py, tools/schema/schema.py
Allows providing message for reference documentation, add it for flask-framework.
-----
=> feat: add doc_slug to init

docs/tutorials/getting-started-with-flask.rst
-----
Found a couple of small mistakes:
- The instructions for a code editor were already in the generalised setup instructions so I removed it from the tutorial
- The rock size was based on an arm64 rock, now I fixed it for the amd64 rock
- Minor grammar/ styling
=> small fixes

rockcraft/commands/init.py, tests/unit/test_cli.py
-----
Building dependencies should be in the part `flask-framework/dependencies`
=> Correct dependencies, as they are in another part

README.rst
=> chore: point README to doc.ubuntu.com/rockcraft

.github/workflows/tests.yaml, .github/workflows/tiobe.yaml, Makefile
General cleanup, brings in the best from:
- snapcraft project setup
- craft parts Makefile
- remove Windows test
-----
=> ci: add future support for tiobe

docs/how-to/chisel/create-slice.rst, docs/how-to/code/create-slice/openssl.yaml
Updated tutorial "How to create a package slice for Chisel" to reflect updates in chisel-releases effecting our docs tests.
-----
=> Fixed tutorial how to create a package slice for chisel

docs/tutorial/code/node-app/task.yaml, docs/tutorial/node-app.rst
Add a paragraph with `curl` instructions for the case where the tutorial is being performed on a Multipass VM.
Fixes #626
-----
=> docs: clarify steps to verify node app in VM

docs/explanation/pebble.rst, requirements-dev.txt, requirements-doc.txt, requirements.txt, rockcraft/models/project.py, setup.cfg
=> build(deps): set proper versions of craft libs

.github/renovate.json5
=> ci: update renovate config from starbase

docs/how-to/rocks/add-internal-user-to-a-rock.rst
-----
Just a few typos fixed in https://documentation.ubuntu.com/rockcraft/en/latest/how-to/rocks/add-internal-user-to-a-rock/
=> docs: fix typos in how to guide

pyproject.toml, rockcraft/extensions/go.py, rockcraft/extensions/gunicorn.py
=> A couple of ruff-related updates

docs/.wordlist.txt, docs/reuse/tutorial/setup.rst, docs/tutorial/code/flask/task.yaml, docs/tutorial/flask.rst
-----
Implements the findings from the UX research
=> Implement ux research for flask-framework tutorial

.github/workflows/snap.yaml, .github/workflows/spread-manual.yaml, .github/workflows/spread.yaml
=> chore(ci): move actions from snapcore to canonical

.github/workflows/security-scan.yaml, osv-scanner.toml, requirements-jammy.txt
=> ci: add security scan workflow

docs/tutorial/code/django/task.yaml, docs/tutorial/django.rst, rockcraft/extensions/gunicorn.py, tests/spread/rockcraft/extension-django/task.yaml, tests/unit/extensions/test_gunicorn.py
-----
Now that we have completed the Django tutorial for Charmcraft and Rockcraft and added other documentation, Django is ready to be stable.
=> make django stable

docs/.wordlist.txt, docs/conf.py, docs/reference/changelog.rst, docs/reference/index.rst, docs/reuse/tutorial/setup.rst, docs/tutorial/django.rst, docs/tutorial/fastapi.rst, docs/tutorial/flask.rst
=> docs: add changelog with notes for 1.6.0

rockcraft/templates/simple/rockcraft.yaml.j2, tests/unit/test_cli.py
=> feat: update 'rockcraft init' base to 24.04

.github/workflows/tests.yaml, rockcraft/utils.py, snap/snapcraft.yaml, tests/integration/plugins/python_source/setup.py, tests/spread/rockcraft/plugin-python-3.6/src/setup.py, tests/spread/rockcraft/plugin-python/src/setup.py, tests/unit/test_utils.py
=> build(snap): update snap to core24

.github/workflows/spread-manual.yaml, requirements-dev.txt, requirements-doc.txt, requirements.txt, rockcraft/cli.py, rockcraft/services/__init__.py, rockcraft/services/remotebuild.py, rockcraft/services/service_factory.py, tests/spread/rockcraft/remote-build/task.yaml
=> feat: add the remote-build command

requirements-dev.txt, requirements-doc.txt, requirements.txt
=> build(deps): update with freeze-requirements.sh

docs/how-to/index.rst, docs/how-to/outsource-rock-builds-to-launchpad.rst, docs/reference/rockcraft.yaml.rst
=> docs: add remote-build how-to

docs/release-notes/rockcraft-1-8-0.rst
=> docs: add remote build how-to to 1.8.0 release notes

docs/conf.py
---
Add a "Give feedback" button to the top of the RTD site that links the user to a GitHub issue form to describe any feedback they have about a particular docs page.
=> feat(docs): add feedback button

docs/conf.py, docs/redirects.txt, pyproject.toml, uv.lock
=> feat(docs): add redirects

rockcraft/extensions/_constants.py, rockcraft/extensions/_utils.py, rockcraft/extensions/gunicorn.py, tests/spread/rockcraft/extension-django/task.yaml, tests/unit/extensions/test_gunicorn.py
* fix: bare base gunicorn based extensions
* chore: raise notimplemented error for unknown base
* chore: scenario cleanup
---
Addresses: https://github.com/canonical/rockcraft/pull/839#issuecomment-2742598693
> Can we get that PR also landed on feature/pro-sources branch too ? I'll need it for a demo along with pro feature
=> fix: bare base gunicorn based extensions (#839)

docs/redirects.txt, docs/release-notes/index.rst, docs/release-notes/rockcraft-1-10-0.rst, docs/release-notes/rockcraft-1-10.rst, docs/release-notes/rockcraft-1-7.rst, docs/release-notes/rockcraft-1-8.rst, docs/release-notes/rockcraft-1-9.rst
=> docs: add release notes for 1.10.0

docs/how-to/get-started.rst
---
This PR adds a link at the bottom of the "getting started" guide to link it to the "hello world" tutorial.
---
See [built page](https://canonical-ubuntu-documentation-library--851.com.readthedocs.build/rockcraft/en/851/how-to/get-started/#testing-rockcraft)
=> docs: link the "hello-world" example in "getting started"

.github/workflows/tics.yaml, .gitignore, .pre-commit-config.yaml, Makefile, common.mk, docs/release-notes/index.rst, pyproject.toml, tests/testing/project.py, uv.lock
=> chore(merge): starbase into main

.github/workflows/schema.yaml, Makefile, pyproject.toml, rockcraft/models/project.py, schema/rockcraft.json, tests/spread/foreign/big/rockcraft.yaml, tests/spread/manual/repo-overlay/rockcraft.yaml, tests/spread/rockcraft/destructive/rockcraft.yaml, tests/spread/rockcraft/plugin-jlink/bare-build-2404/rockcraft.yaml, tests/spread/rockcraft/plugin-jlink/base-2404/rockcraft.yaml, tests/spread/rockcraft/plugin-python/bare-build-2004/rockcraft.yaml, tests/spread/rockcraft/plugin-python/bare-build-2204/rockcraft.yaml, tests/spread/rockcraft/plugin-python/base-2004/rockcraft.yaml, tests/spread/rockcraft/plugin-python/base-2204/rockcraft.yaml, tests/spread/rockcraft/plugin-python/base-2404/rockcraft.yaml, uv.lock
=> feat(project): update Platform schema  

docs/release-notes/index.rst, docs/release-notes/rockcraft-1-11.rst
=> docs: release notes for 1.11.0

docs/how-to/web-app-rocks/index.rst, docs/release-notes/index.rst, docs/release-notes/rockcraft-1-12.rst
This is currently targeting another branch as we try to finalize actual code updates there (these new docs already account for this).
---
=> docs: release notes for 1.12

docs/tutorial/springboot.rst, rockcraft/templates/spring-boot-framework/rockcraft.yaml.j2
=> docs: Fix summary line for Spring Boot template

docs/conf.py, docs/reference/plugins.rst, docs/reference/plugins/ant_plugin.rst, docs/reference/plugins/maven_plugin.rst, docs/reference/rockcraft.yaml.rst, docs/release-notes/rockcraft-1-10.rst, docs/tutorial/hello-world.rst, pyproject.toml, schema/rockcraft.json, uv.lock
=> Update dependencies, bring in pydantic-kitbash

tests/data/flask/requirements.txt, tests/spread/rockcraft/extension-flask-uncomment-blocks/requirements.txt, tests/spread/rockcraft/extension-flask/requirements.txt
---
A quick PR to fix the version of Flask to make OSV-scanner happy.
=> chore: pin all flask versions for osv warning

docs/conf.py, docs/reference/plugins.rst, pyproject.toml, schema/rockcraft.json, snap/snapcraft.yaml, tests/unit/conftest.py, tests/unit/services/test_lifecycle.py, tests/unit/test_cli.py, uv.lock
=> build(deps): update all dependencies

docs/reference/extensions/spring-boot-framework.rst, rockcraft/extensions/springboot.py, rockcraft/templates/spring-boot-framework/rockcraft.yaml.j2, tests/unit/extensions/test_springboot.py
---
Add missing files migrate and migrate.sh files if they are in the root directory of the Spring Boot project.
=> fix: add missing migrate and migrate.sh

docs/reference/rockcraft.yaml.rst, docs/release-notes/index.rst, docs/release-notes/rockcraft-1-14.rst, pyproject.toml
=> docs: release notes for 1.14.0
